### ISSUE TITLE
numbers for Gompertz curve

### ISSUE THREAD

**Issue by MaggiK** [pearselab/r-intro-MaggiK#1]
Can you give us numbers (and possibly a correct answer) to plug into the Gompertz curve equation? I think that would help to see if my equation and plots work because I don't really know what normal values of a and b are.

**Comment by willpearse** [comment]
I just looked at your code, and it looks like your function is fine. You can see exemplar values at the Wikipedia page (!) https://en.wikipedia.org/wiki/Gompertz_function

While I'm here, try to avoid using `=` to assign values to objects. For example, consider:

```
pop_growth <- function(a, b, c, t) { #...rest of code
```

...which is better than using:

```
pop_growth=function(a, b, c, t) { #...rest of code
```

This is because `=` isn't as flexible to re-program as `<-`, and so sometimes the two will do slightly different things. It's annoying, but it's best to get into the habit of typing `<-`. Honest, it's worth it!

**Comment by MaggiK** [comment]
Ok sorry. I will start using <- I forget because I am used to using =.
Maggi

**Comment by willpearse** [comment]
Don't be sorry! You're doing very well, and the purpose of a class is to learn anyway :D

**Comment by willpearse** [comment]
No worries!
